# Le nom donné au service MariaDB/MySQL (uniquement des caractères alphanumériques en minuscules).
db:
    # Le type de votre service (mariadb), qui utilise le format
    # 'type:version'. Assurez-vous de consulter la documentation de MariaDB/MySQL
    # (https://docs.platform.sh/add-services/mysql.html#supported-versions)
    # lors du choix d'une version. Si vous spécifiez un numéro de version qui n'est pas disponible,
    # la CLI renverra une erreur.
    type: mysql:5.7
    # L'attribut disk représente la taille du disque persistant (en Mo) alloué au service.
    disk: 2048

